name: Build SA-MP Gamemode

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Pawn Compiler
        run: |
          git clone --depth=1 https://github.com/pawn-lang/compiler.git compiler
          cd compiler
          mkdir build
          cd build
          cmake ..
          make

      - name: Compile Gamemode
        run: |
          ./compiler/build/pawncc \
            gamemodes/gamemode.pwn \
            -ilegacy \
            -ogamemodes/gamemode.amx

      - name: Upload AMX
        uses: actions/upload-artifact@v4
        with:
          name: gamemode
          path: gamemodes/gamemode.amx
