name: Build SA-MP Gamemode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget unzip curl build-essential

      - name: Download Pawn Compiler
        run: |
          git clone https://github.com/openmultiplayer/compiler.git
          cd compiler
          mkdir build
          cd build
          cmake ..
          make
          sudo cp pawncc /usr/local/bin/
          pawncc -v

      - name: Compile Gamemode
        run: |
          pawncc gamemodes/gamemode.pwn -i./pawno/include -o gamemode.amx

      - name: Upload AMX
        uses: actions/upload-artifact@v4
        with:
          name: gamemode-amx
          path: gamemode.amx
          
