name: Build SA-MP Gamemode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/openmultiplayer/compiler:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            pawncc gamemodes/gamemode.pwn -i./legacy -i./gamemodes -ogamemode.amx

      - name: Upload AMX
        uses: actions/upload-artifact@v4
        with:
          name: gamemode-amx
          path: gamemode.amx
