name: Compile SP-RP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Compiler
        run: |
          git clone https://github.com/pawn-lang/compiler.git
          echo "Compiler downloaded"

      - name: Show Project
        run: |
          pwd
          ls -la
          find gamemodes -type f

      - name: Done
        run: echo "Ready for next step"
