name: Build Ryzex Mobile RP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake make clang

      - name: Clone Pawn compiler
        run: |
          git clone https://github.com/compuphase/pawn.git

      - name: Find compiler
        run: |
          echo "Current directory:"
          pwd
          echo ""
          echo "Repository tree:"
          ls -R

      - name: Complete
        run: echo "Done"
