name: Build Ryzex Mobile RP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y git curl unzip

      - name: Show pawn.json
        run: cat pawn.json
